services:
  api-server:
    image: leegeonmin/myrestserver:latest
    container_name: myrestserver-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "18088:8088"
    networks:
      - my-network
    depends_on:
      - db

  db:
    image: leegeonmin/mysql-custom:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "13306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

volumes:
  mysql-data:
    external: true # 기존 볼륨을 사용할 경우 true

networks:
  my-network:
    external: true # 기존 네트워크에 합류 true

# run (실행)
# docker compose
# docker compose --env-file .env up -d

# 서비스 종료
# docker compose down
